### ISSUE TITLE
Example Data Inquiry

### ISSUE THREAD

**Issue by RoboticsZhang** [xcn700418/SAR_imaging#2]
Could you supplement some example data, such as the ”0711_data.mat“ in BPA.m? Thank you very much!

**Comment by xcn700418** [comment]
Hello, there is a MATLAB script in MMwave studio to process the raw data(".bin" file) captured from radar sensor, you will get the ".mat" file using the script,. Sorry I cannot find the data since it has been quite some time and I am no longer work in this field.

**Comment by RoboticsZhang** [comment]
Got it, thank you very much.
